name: ffmpeg_kit_min_gpl
description: FFmpeg Kit for Flutter. Supports Android, iOS and macOS platforms.
repository: https://github.com/meetleev/flutter-ffmpeg-kit.git
homepage: https://github.com/meetleev
version: 6.0.3+2

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.arthenica.ffmpegkit.flutter
        pluginClass: FFmpegKitFlutterPlugin

dependencies:
  ffmpeg_kit_flutter_platform_interface: ^0.2.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.5
